[package]
name = "boron"
version = "0.0.1"
authors = ["AloÃ¯s Micard <alois@micard.lu>"]
edition = "2018"

[dependencies]
failure = "0.1.8"
serde_json = "1.0.55"

[dependencies.clap]
version = "2.33.1"
default-features = false